"""Pack the rendered sheet frames into atlases and write sprites/knight.js for the game.

Per helm: base (team parts grey), team mask and metal mask. Per plume: one plume layer (all team colour, already occluded
by a standard helm). Atlases are WebP data URLs so the game still works from file:// and the canvas never gets tainted.
Masks keep only their alpha, which WebP stores compactly. Also measures the anchor (feet) and head top."""
import base64, io, json, os, sys
from PIL import Image
HERE = os.path.dirname(os.path.abspath(__file__))
SRC = sys.argv[1] if len(sys.argv) > 1 else os.path.join(HERE, 'sheet')
OUT = os.path.join(HERE, '..', '..', 'sprites'); os.makedirs(OUT, exist_ok=True)
meta = json.load(open(os.path.join(SRC, 'sheet.json')))
n = len(meta['frames']); cell = meta['cell']; cols = 10; rows = (n + cols - 1) // cols
total = 0

def atlas(prefix, layer, white=False):
    a = Image.new('RGBA', (cols * cell, rows * cell), (0, 0, 0, 0))
    for i in range(n):
        f = os.path.join(SRC, f'{prefix}_{layer}_{i:03d}.png')
        if not os.path.exists(f): return None
        im = Image.open(f).convert('RGBA')
        if white:  # coverage only: white RGB, alpha from the render
            im = Image.merge('RGBA', (*[Image.new('L', im.size, 255)] * 3, im.split()[3]))
        a.paste(im, ((i % cols) * cell, (i // cols) * cell))
    return a

def durl(im, lossless=False):
    global total
    b = io.BytesIO(); im.save(b, 'WEBP', lossless=lossless, quality=92 if not lossless else 80, method=6)
    total += len(b.getvalue()); return 'data:image/webp;base64,' + base64.b64encode(b.getvalue()).decode()

helms, plumes, anchor = {}, {}, None
for h in meta['helms']:
    base = atlas('helm_' + h, 'base')
    if base is None: print('skip helm', h); continue
    if anchor is None or h == 'great':
        s0 = base.crop((0, 0, cell, cell)); bb = s0.split()[3].getbbox(); anchor = (bb[3] - 6, bb[1])
    ent = {'base': durl(base), 'mask': durl(atlas('helm_' + h, 'mask', True))}
    met = atlas('helm_' + h, 'metal', True)
    if met is not None: ent['metal'] = durl(met)
    helms[h] = ent; base.save(os.path.join(SRC, f'_atlas_{h}.png'))
for p in meta['plumes']:
    pl = atlas('plume_' + p, 'plume')
    if pl is None: print('skip plume', p); continue
    plumes[p] = durl(pl)
# per-anim frame offsets inside a direction block
off, o = {}, 0
for an, cnt in meta['anims']: off[an] = [o, cnt]; o += cnt
js = ('// generated by art/blender/pack.py from art/blender/knight.py. Do not edit.\n'
      'window.CK_SPRITES=' + json.dumps({'knight': {'cell': cell, 'cols': cols, 'dirs': meta['dirs'], 'per': o, 'anims': off,
                                           'anchorY': anchor[0], 'topY': anchor[1], 'helms': helms, 'plumes': plumes}}) + ';\n')
open(os.path.join(OUT, 'knight.js'), 'w').write(js)
print(f'packed {n} frames x {len(helms)} helms + {len(plumes)} plumes, atlas {cols * cell}x{rows * cell}, images {total // 1024} KB, js {len(js) // 1024} KB, anchor {anchor}')
