"""Pack the rendered sheet frames into two atlases (base, mask) and write sprites/knight.js for the game.
The atlases are embedded as data URLs so the game still works from file:// and the canvas never gets tainted.
Also measures the anchor (feet) and head top so the game can place names and hearts."""
import base64, io, json, os, sys
from PIL import Image
HERE = os.path.dirname(os.path.abspath(__file__))
SRC = sys.argv[1] if len(sys.argv) > 1 else os.path.join(HERE, 'sheet')
OUT = os.path.join(HERE, '..', '..', 'sprites'); os.makedirs(OUT, exist_ok=True)
meta = json.load(open(os.path.join(SRC, 'sheet.json')))
n = len(meta['frames']); cell = meta['cell']; cols = 10; rows = (n + cols - 1) // cols
atl = {}
for layer in ('base', 'mask'):
    a = Image.new('RGBA', (cols * cell, rows * cell), (0, 0, 0, 0))
    for i in range(n):
        im = Image.open(os.path.join(SRC, f'{layer}_{i:03d}.png')).convert('RGBA')
        if layer == 'mask':  # keep only white where the team parts are; alpha from coverage
            px = im.load()
            for y in range(im.height):
                for x in range(im.width):
                    r, g, b, al = px[x, y]; px[x, y] = (255, 255, 255, al)
        a.paste(im, ((i % cols) * cell, (i // cols) * cell))
    atl[layer] = a
# anchor from the south idle frame: feet = lowest opaque row, centre = mean x of that band
s0 = atl['base'].crop((0, 0, cell, cell)); al = s0.split()[3]; bbox = al.getbbox()
feet = bbox[3] - 6; top = bbox[1]
def durl(im):
    b = io.BytesIO(); im.save(b, 'PNG', optimize=True); return 'data:image/png;base64,' + base64.b64encode(b.getvalue()).decode(), len(b.getvalue())
bu, bn = durl(atl['base']); mu, mn = durl(atl['mask'])
js = ('// generated by art/blender/pack.py from art/blender/knight.py. Do not edit.\n'
      'window.CK_SPRITES=' + json.dumps({'knight': {'cell': cell, 'cols': cols, 'dirs': meta['dirs'], 'anims': meta['anims'], 'frames': meta['frames'],
                                           'anchorY': feet, 'topY': top, 'base': bu, 'mask': mu}}) + ';\n')
open(os.path.join(OUT, 'knight.js'), 'w').write(js)
atl['base'].save(os.path.join(SRC, '_atlas_base.png')); atl['mask'].save(os.path.join(SRC, '_atlas_mask.png'))
print(f'packed {n} frames, atlas {cols * cell}x{rows * cell}, base {bn // 1024} KB, mask {mn // 1024} KB, anchor {feet}, top {top}')
