/* A winding, keyboard/controller navigable chapter map and skippable story cards. */
(function(root){
 'use strict';
 function mount(options){
  const campaign=options.campaign,C=root.CKCampaign,doc=options.document||document;
  const style=doc.createElement('style');style.textContent=`
  #campaignMap,#campaignStory,#campaignResult{z-index:12;background:rgba(20,12,34,.95)}
  .campaign-panel{width:min(1040px,96%);max-width:96%;min-width:0;margin:auto;gap:10px;overflow-x:hidden}
  .campaign-panel h2{margin:0;color:var(--custard);font:32px 'Lilita One',Impact,sans-serif}
  .campaign-panel p{margin:0;line-height:1.4}.campaign-world{position:relative;min-width:0;max-width:100%;height:310px;border:3px solid var(--ink);border-radius:18px;background:radial-gradient(ellipse at 22% 62%,#526d49,#293347 64%,#352147);overflow:auto}.campaign-route{position:relative;min-width:620px;width:100%;height:100%}.campaign-scroll-hint{display:none}
  .campaign-world svg{position:absolute;inset:0;width:100%;height:100%}.campaign-node{position:absolute;transform:translate(-50%,-50%);width:92px;padding:6px 3px;font:700 12px Nunito,sans-serif;color:#fff7e0;background:#3D2B57;border:3px solid #221733;border-radius:12px;cursor:pointer}
  .campaign-node b{display:block;font-size:21px}.campaign-node.completed{background:#245b52}.campaign-node[aria-pressed=true]{outline:3px solid #FFD23F;outline-offset:3px}.campaign-node:disabled{opacity:.45;cursor:default}.campaign-brief{background:#221733;padding:12px;border-radius:12px;min-height:110px}.campaign-brief h3{margin:0 0 7px;color:#FFD23F}.campaign-spoons{margin:8px 0;padding-left:24px;font-size:14px}.campaign-spoons li{padding:2px 0}.campaign-dialogue{padding:18px 12px;background:#221733;border-radius:12px;font-size:18px;min-height:100px}.campaign-story-actions{display:flex;gap:8px;flex-wrap:wrap}.campaign-next{color:#2EC4B6;font-weight:800}.campaign-save-warning{color:#FF8FB1;font-weight:800}
  #campaignHUD{position:absolute;top:82px;left:50%;transform:translateX(-50%);max-width:80%;pointer-events:none;z-index:2;background:#221733e6;border:2px solid #FFD23F;border-radius:10px;padding:6px 12px;text-align:center;font-weight:900;font-size:14px;color:#FFF7E0}
  .campaign-factions{font-size:13px}.campaign-factions p{margin:6px 0}.campaign-panel .btn{min-height:42px}
  @media(max-width:650px){.campaign-world{height:270px}.campaign-node{width:65px;font-size:10px}.campaign-node b{font-size:17px}.campaign-panel{padding:12px}.campaign-panel h2{font-size:25px}.campaign-scroll-hint{display:block;font-size:12px;color:#C9B9E6}#campaignHUD{font-size:12px;max-width:92%;top:74px}}
  `;doc.head.appendChild(style);
  const host=options.host||doc.getElementById('stage')||doc.body;
  function el(tag,text,className){const e=doc.createElement(tag);if(text!==undefined)e.textContent=text;if(className)e.className=className;return e;}
  function screen(id){const e=el('div',undefined,'overlay');e.id=id;e.hidden=true;const p=el('section',undefined,'panel wide campaign-panel');p.setAttribute('aria-label','The Great Pudding War');e.appendChild(p);host.appendChild(e);return {e,p};}
  const map=screen('campaignMap'),story=screen('campaignStory'),result=screen('campaignResult'),hud=el('div');hud.id='campaignHUD';hud.hidden=true;hud.setAttribute('aria-live','polite');host.appendChild(hud);
  let selected=campaign.save.selected,dialogueIndex=0,pendingStart=null,lastHud='';
  function button(label,action,back=false){const b=el('button',label,'btn');b.type='button';b.onclick=action;if(back)b.dataset.back='true';return b;}
  function show(s){[map,story,result].forEach(x=>x.e.hidden=x!==s);hud.hidden=true;const b=s.p.querySelector('.campaign-node[aria-pressed="true"]')||s.p.querySelector('button:not(:disabled)');if(b)b.focus();}
  function close(){[map,story,result].forEach(x=>x.e.hidden=true);hud.hidden=true;}
  function saveWarning(p){if(campaign.saveError)p.appendChild(el('p','Progress is available this session. Your browser could not save it; keep this game open to retain it.','campaign-save-warning'));}
  function describe(n){const box=el('div',undefined,'campaign-brief');box.appendChild(el('h3',(n.optional?'Optional · ':'')+n.title));box.appendChild(el('p',n.objective));const list=el('ol',undefined,'campaign-spoons');const owned=campaign.save.results[n.id];n.spoons.forEach((s,i)=>list.appendChild(el('li',(owned&&owned.spoons[i]?'✓ ':'')+s)));box.appendChild(list);const checkpoint=campaign.save.checkpoint;box.appendChild(button(checkpoint&&checkpoint.id===n.id?'Continue from saved test':'Play encounter',()=>brief(n.id,true)));if(owned&&owned.spoons[0])box.appendChild(button('Replay from beginning',()=>brief(n.id,false)));box.appendChild(button('Read story again',()=>storyCard(n.dialogue,()=>open(n.id),'Back to map')));return box;}
  function open(id){options.onOpen&&options.onOpen();close();selected=id&&campaign.unlocked(id)?id:campaign.unlocked(campaign.save.selected)?campaign.save.selected:(campaign.next()||C.nodes[0]).id;campaign.select(selected);map.p.replaceChildren();map.p.appendChild(el('h2','The Great Pudding War'));map.p.appendChild(el('p','A Very Bad Banquet · recover the Golden Spoon and save the bakery.'));const next=campaign.next();map.p.appendChild(el('p',next?'Next destination: '+next.title:'The rice road is open. Replay encounters to earn the remaining spoons.','campaign-next'));
   const world=el('div',undefined,'campaign-world'),route=el('div',undefined,'campaign-route');world.appendChild(route);const ns='http://www.w3.org/2000/svg',svg=doc.createElementNS(ns,'svg');svg.setAttribute('viewBox','0 0 100 100');svg.setAttribute('preserveAspectRatio','none');svg.setAttribute('aria-hidden','true');
   for(const n of C.nodes)for(const from of n.requires){const a=C.byId[from],path=doc.createElementNS(ns,'path');path.setAttribute('d',`M ${a.at[0]} ${a.at[1]} Q ${(a.at[0]+n.at[0])/2} ${Math.min(a.at[1],n.at[1])-9} ${n.at[0]} ${n.at[1]}`);path.setAttribute('stroke',n.optional?'#C9B9E6':'#FFD23F');path.setAttribute('stroke-width','1.2');path.setAttribute('fill','none');if(n.optional)path.setAttribute('stroke-dasharray','2 2');svg.appendChild(path);}
   const rejoin=doc.createElementNS(ns,'path');rejoin.setAttribute('d','M 45 24 Q 62 24 56 53');rejoin.setAttribute('stroke','#C9B9E6');rejoin.setAttribute('stroke-width','1.2');rejoin.setAttribute('stroke-dasharray','2 2');rejoin.setAttribute('fill','none');svg.appendChild(rejoin);
   route.appendChild(svg);C.nodes.forEach((n,i)=>{const owned=campaign.save.results[n.id];const b=button('',()=>open(n.id));b.className='campaign-node'+(owned&&owned.spoons[0]?' completed':'');b.style.left=n.at[0]+'%';b.style.top=n.at[1]+'%';b.setAttribute('aria-label',(i+1)+'. '+n.title+(n.optional?', optional':'')+(campaign.unlocked(n.id)?', playable':', locked'));b.setAttribute('aria-pressed',String(selected===n.id));b.disabled=!campaign.unlocked(n.id);b.appendChild(el('b',n.optional?'↗':String(i+1)));b.appendChild(el('span',n.id==='rind'?'Rice fortress':n.id==='steve'?'Steve’s cage':n.id==='stirling'?'Sir Stirling':n.id==='biscuit'?'Biscuit toll':n.id==='puddings'?'Puddings':n.id==='banquet'?'Banquet':n.id==='guard'?'Rice guard':'Flan bridge'));b.appendChild(el('div',owned?owned.spoons.map(s=>s?'🥄':'·').join(' '):'· · ·'));route.appendChild(b);});map.p.appendChild(world);map.p.appendChild(el('p','Swipe or scroll the route sideways to see the next destination.','campaign-scroll-hint'));map.p.appendChild(describe(C.byId[selected]));
   const assistance=button('Assistance: '+(campaign.save.assist?'on · extra health, slower arrows and longer boss warnings':'off'),()=>{campaign.assist(!campaign.save.assist);open(selected);});assistance.setAttribute('aria-pressed',String(campaign.save.assist));map.p.appendChild(assistance);map.p.appendChild(el('p','Assistance can finish the story and earn the same spoons. Completed encounters show whether assistance was used.','note'));
   const details=el('details',undefined,'campaign-factions');details.appendChild(el('summary','The dessert kingdoms and the missing Spoon'));C.factions.forEach(f=>details.appendChild(el('p',f.name+': '+f.text)));details.appendChild(el('p','Angelic Delight, Jelly Marshes, Crumble Crags and Trifle Citadel are story destinations beyond this playable chapter.'));map.p.appendChild(details);const owned=campaign.save.results[selected];if(owned&&owned.assisted)map.p.appendChild(el('p','This encounter has been completed with assistance.','note'));saveWarning(map.p);map.p.appendChild(button('Back to menu',()=>{close();options.onExit&&options.onExit();},true));show(map);
  }
  function storyCard(lines,done,endLabel='Start encounter'){
   dialogueIndex=0;story.p.replaceChildren();story.p.appendChild(el('h2','The Official History, According to the Winner'));const line=el('p',lines[0]||'', 'campaign-dialogue');story.p.appendChild(line);const row=el('div',undefined,'campaign-story-actions');const advance=button(lines.length>1?'Next line':endLabel,()=>{dialogueIndex++;if(dialogueIndex>=lines.length){done();return;}line.textContent=lines[dialogueIndex];advance.textContent=dialogueIndex===lines.length-1?endLabel:'Next line';});row.appendChild(advance);row.appendChild(button('Skip story',done));story.p.appendChild(row);story.p.appendChild(button('Back to map',()=>open(selected),true));show(story);
  }
  function brief(id,resume=true){selected=id;campaign.select(id);const n=C.byId[id];pendingStart=()=>{close();options.start(id,resume);hud.hidden=false;refresh();};storyCard(n.dialogue,pendingStart);const ol=el('ol',undefined,'campaign-spoons');n.spoons.forEach(s=>ol.appendChild(el('li',s)));story.p.insertBefore(ol,story.p.children[2]);story.p.insertBefore(el('p',n.objective),ol);}
  function ended(r){close();result.p.replaceChildren();const n=C.byId[r.id];result.p.appendChild(el('h2',r.won?'Encounter complete':'Try again'));result.p.appendChild(el('p',n.title));result.p.appendChild(el('p',r.won?r.added.length+' new spoon'+(r.added.length===1?'':'s')+' earned. Your spoons are saved independently.':r.reason||n.tip));const list=el('ol',undefined,'campaign-spoons');const saved=campaign.save.results[r.id];n.spoons.forEach((s,i)=>list.appendChild(el('li',(saved&&saved.spoons[i]?'✓ ':'')+s)));result.p.appendChild(list);if(r.assisted)result.p.appendChild(el('p','Assistance was enabled.','note'));saveWarning(result.p);
   if(r.won){result.p.appendChild(button('Read what happens next',()=>storyCard(r.outro,()=>open(r.next||r.id),'Open story map')));if(r.next)result.p.appendChild(button('Continue: '+C.byId[r.next].title,()=>brief(r.next,false)));result.p.appendChild(button('Replay for spoons',()=>brief(r.id,false)));}else{result.p.appendChild(button(r.checkpoint?'Retry from checkpoint':'Retry now',()=>{close();options.start(r.id,true);hud.hidden=false;refresh();}));result.p.appendChild(button('Retry with assistance',()=>{campaign.assist(true);close();options.start(r.id,true);hud.hidden=false;refresh();}));result.p.appendChild(el('p',n.tip,'note'));}
   result.p.appendChild(button('Story map',()=>open(r.next||r.id),true));show(result);
  }
  function refresh(){const r=campaign.run;if(!r||r.status!=='playing'){hud.hidden=true;return;}const text=campaign.objective();if(text!==lastHud){hud.textContent=text;lastHud=text;}hud.hidden=false;}
  return {open,close,brief,ended,refresh,screens:['campaignMap','campaignStory','campaignResult'],destroy(){close();[map.e,story.e,result.e,hud,style].forEach(e=>e.remove());}};
 }
 root.CKCampaignUI={mount};
})(typeof globalThis!=='undefined'?globalThis:this);
