/* Deterministic shared-household collection. Does not mutate legacy coin progression or combat. */
(function(root,factory){const api=factory();if(typeof module==='object'&&module.exports)module.exports=api;else root.CKCollection=api;})(typeof globalThis!=='undefined'?globalThis:this,()=>{
 'use strict';
 const items=[
 {id:'tea-towel',kind:'cape',value:'teaTowel',name:'Tea Towel',goal:3,description:'Checked kitchen cloth. One very oversized peg.'},
 {id:'burnt-toast',kind:'cape',value:'burntToast',name:'Burnt Toast',goal:3,description:'Crisp at the edges. Heroically buttered in the middle.'},
 {id:'golden-whisk',kind:'blade',value:'goldenWhisk',name:'Golden Whisk',goal:8,description:'A proper balloon whisk. Same reach. More baking.'},
 {id:'rooster-crown',kind:'helm',value:'roosterCrown',name:'Rooster Crown',goal:12,description:'Technically a helmet. Legally a chicken.'},
 {id:'rice-guard',kind:'helm',value:'riceGuard',name:'Rice Guard',goal:8,milestones:['rice-chapter'],description:'A pudding bowl, rice grains and a severe little visor.'},
 {id:'steve-strut',kind:'pose',value:'steveStrut',name:'Steve Strut',goal:4,milestones:['steve-rescue','cup-complete'],description:'An extremely dignified chicken strut on the results podium.'}
 ];
 const ids=items.map(x=>x.id),count=n=>Number.isSafeInteger(n)&&n>=0?Math.min(n,1e8):0;
 const profileKeys=['helm','plume','metal','emblem','color','cape','blade','chick','pose'];
 const cleanOutfit=p=>p&&typeof p==='object'&&!Array.isArray(p)?Object.fromEntries(profileKeys.filter(k=>typeof p[k]==='string'&&p[k].length<50&&/^[\w#-]+$/.test(p[k])).map(k=>[k,p[k]])):null;
 function normalize(raw){const r=raw&&typeof raw==='object'&&!Array.isArray(raw)?raw:{};return {version:1,completed:count(r.completed),choice:ids.slice(0,2).includes(r.choice)?r.choice:null,pinned:ids.includes(r.pinned)?r.pinned:null,progress:Object.fromEntries(items.map(i=>[i.id,Math.min(i.goal,count(r.progress&&r.progress[i.id]))])),owned:[...new Set((Array.isArray(r.owned)?r.owned:[]).filter(x=>ids.includes(x)))],receipts:[...new Set((Array.isArray(r.receipts)?r.receipts:[]).filter(x=>typeof x==='string'&&x.length>0&&x.length<=100))].slice(-512),milestones:[...new Set((Array.isArray(r.milestones)?r.milestones:[]).filter(x=>['rice-chapter','steve-rescue','cup-complete'].includes(x)))],presets:Array.from({length:3},(_,i)=>cleanOutfit(r.presets&&r.presets[i]))};}
 function owns(raw,kind,value){const item=items.find(x=>x.kind===kind&&x.value===value);return !!item&&normalize(raw).owned.includes(item.id);}
 function pin(raw,id){const s=normalize(raw);if(ids.includes(id)&&!s.owned.includes(id))s.pinned=id;return s;}
 function choose(raw,id){const s=normalize(raw);if(s.completed>0&&!s.choice&&ids.slice(0,2).includes(id)){s.choice=id;if(!s.owned.includes(id))s.owned.push(id);}return s;}
 function apply(raw,event){const s=normalize(raw),unlocked=[];if(!event||event.participated!==true||typeof event.roundId!=='string'||!event.roundId||event.roundId.length>100||s.receipts.includes(event.roundId))return {state:s,unlocked,applied:false};
 s.completed++;s.receipts.push(event.roundId);s.receipts=s.receipts.slice(-512);
 const grant=id=>{if(!s.owned.includes(id)){s.owned.push(id);unlocked.push(id);}};
 if(s.pinned&&!s.owned.includes(s.pinned)){const item=items.find(i=>i.id===s.pinned);s.progress[item.id]=Math.min(item.goal,s.progress[item.id]+1);if(s.progress[item.id]===item.goal)grant(item.id);}
 for(const m of Array.isArray(event.milestones)?event.milestones:[]){if(!['rice-chapter','steve-rescue','cup-complete'].includes(m))continue;if(!s.milestones.includes(m))s.milestones.push(m);for(const item of items)if(item.milestones&&item.milestones.includes(m))grant(item.id);}
 return {state:s,unlocked,applied:true};}
 function savePreset(raw,index,outfit){const s=normalize(raw);if(Number.isInteger(index)&&index>=0&&index<3)s.presets[index]=cleanOutfit(outfit);return s;}
 function merge(a,b){a=normalize(a);b=normalize(b);return normalize({completed:Math.max(a.completed,b.completed),choice:a.choice||b.choice,pinned:a.pinned||b.pinned,owned:[...a.owned,...b.owned],milestones:[...a.milestones,...b.milestones],receipts:[...a.receipts,...b.receipts],progress:Object.fromEntries(ids.map(id=>[id,Math.max(a.progress[id],b.progress[id])])),presets:a.presets.map((p,i)=>p||b.presets[i])});}
 const backupKeys=['ck-campaign-v1','ck-progress','ck-collection','ck-profile','ck-profile2','ck-profile3','ck-profile4'];
 function exportBackup(storage){const saves={};for(const k of backupKeys){const v=storage.getItem(k);if(v!==null)saves[k]=JSON.parse(v);}return JSON.stringify({format:'custard-knights-wardrobe',version:1,saves},null,2);}
 function importBackup(storage,text){if(typeof text!=='string'||text.length>200000)throw Error('Choose a Custard Knights wardrobe backup under 200 KB.');let b;try{b=JSON.parse(text);}catch{throw Error('This file is not valid JSON.');}if(!b||b.format!=='custard-knights-wardrobe'||b.version!==1||!b.saves||typeof b.saves!=='object'||Array.isArray(b.saves)||Object.keys(b.saves).some(k=>!backupKeys.includes(k)))throw Error('This is not a supported wardrobe backup.');
 const writes={};for(const [k,v]of Object.entries(b.saves)){if(!v||typeof v!=='object'||Array.isArray(v))throw Error('Invalid save section: '+k);let old={};try{old=JSON.parse(storage.getItem(k)||'{}');}catch{}
 if(k==='ck-campaign-v1'){const Campaign=typeof require==='function'?require('./campaign.js'):globalThis.CKCampaign;if(!Campaign||v.version!==1||!v.results||typeof v.results!=='object'||Array.isArray(v.results)||!Array.isArray(v.receipts)||v.receipts.some(x=>typeof x!=='string'||x.length>120)||Object.entries(v.results).some(([id,r])=>!Campaign.byId[id]||!r||!Array.isArray(r.spoons)||r.spoons.length!==3||r.spoons.some(x=>typeof x!=='boolean')||!Number.isInteger(r.attempts)||r.attempts<0||!(r.best===null||Number.isFinite(r.best)&&r.best>=0)||typeof r.assisted!=='boolean'))throw Error('Invalid campaign progress.');writes[k]=Campaign.merge(old,v);}
 else if(k==='ck-collection'){if(v.version!==1||!Array.isArray(v.owned)||v.owned.some(x=>!ids.includes(x))||!Number.isSafeInteger(v.completed)||v.completed<0||!v.progress||typeof v.progress!=='object'||items.some(i=>!Number.isSafeInteger(v.progress[i.id])||v.progress[i.id]<0||v.progress[i.id]>i.goal)||!Array.isArray(v.receipts)||v.receipts.some(x=>typeof x!=='string'||!x||x.length>100))throw Error('Invalid collection data.');writes[k]=merge(old,v);}
 else if(k==='ck-progress'){if(!['earned','matches','wins'].every(x=>Number.isSafeInteger(v[x])&&v[x]>=0)||!Array.isArray(v.unlocked)||v.unlocked.some(x=>typeof x!=='string'))throw Error('Invalid legacy wardrobe data.');const ch={};for(const key of ['firstWin','parry10','ringout3','raceWin','lksWin','lava5'])ch[key]=Math.max(count(old.ch&&old.ch[key]),count(v.ch&&v.ch[key]));writes[k]={...old,...v,earned:Math.max(count(old.earned),v.earned),matches:Math.max(count(old.matches),v.matches),wins:Math.max(count(old.wins),v.wins),ch,unlocked:[...new Set([...(Array.isArray(old.unlocked)?old.unlocked:[]),...v.unlocked])],receipts:[...new Set([...(Array.isArray(old.receipts)?old.receipts:[]),...(Array.isArray(v.receipts)?v.receipts:[])])].filter(x=>typeof x==='string'&&x.length<=100).slice(-128)};}
 else {const outfit=cleanOutfit(v);if(!outfit||Object.keys(outfit).length<4||Object.keys(v).some(k=>!profileKeys.includes(k)))throw Error('Invalid outfit data.');writes[k]=outfit;}}
 // Validate every section before the first write. Keep an in-memory rollback for storage failures.
 const before=Object.fromEntries(Object.keys(writes).map(k=>[k,storage.getItem(k)]));try{for(const [k,v]of Object.entries(writes))storage.setItem(k,JSON.stringify(v));}catch(e){for(const[k,v]of Object.entries(before))try{v===null?storage.removeItem(k):storage.setItem(k,v);}catch{}throw Error('Could not save this backup. Your existing saves were restored where possible.');}return Object.keys(writes);}
 return {items,normalize,owns,pin,choose,apply,savePreset,merge,cleanOutfit,exportBackup,importBackup};
});
