/* Collection UI uses callbacks so game rendering, seats and profile ownership stay authoritative. */
(function(root){'use strict';const C=()=>root.CKCollection;
function el(tag,text,cls){const n=document.createElement(tag);if(text!==undefined)n.textContent=text;if(cls)n.className=cls;return n;}
function button(label,fn){const b=el('button',label,'btn');b.type='button';b.onclick=fn;return b;}
function mount(container,a){if(!container)throw Error('Collection container required');container.classList.add('ck-collection');let selected=C().items[0].id,notice='',lastTick=0,raf;
 if(!document.getElementById('ck-collection-style')){const s=el('style');s.id='ck-collection-style';s.textContent='.ck-collection{margin-top:20px;color:inherit}.ck-collection .ck-grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(220px,1fr));gap:12px}.ck-collection .ck-card{padding:14px;border:2px solid #76596c;border-radius:14px;background:#fff5dc;color:#291a33}.ck-collection .ck-card[data-pinned=true]{border-color:#d58a1f;box-shadow:0 0 0 2px #ffd23f}.ck-collection .ck-row{display:flex;flex-wrap:wrap;gap:8px;align-items:center}.ck-collection .ck-card p{font-size:14px;line-height:1.4;margin:7px 0}.ck-collection .ck-preview{background:#426351;border-radius:16px;max-width:100%;height:auto}.ck-collection progress{width:100%;height:14px;accent-color:#b17a12}.ck-collection .ck-preview-row{display:flex;flex-wrap:wrap;gap:16px;align-items:end}.ck-collection .ck-message{min-height:1.5em}.ck-collection .ck-choice{background:#ffe293;border:2px solid #946426;border-radius:16px;padding:14px;margin:12px 0}.ck-collection .ck-card button{font-size:13px;padding:7px 10px}.ck-collection .ck-presets{margin:16px 0;display:flex;gap:12px;flex-wrap:wrap}';document.head.appendChild(s);}
 const state=()=>C().normalize(a.getState()),set=s=>{a.setState(s);render();},profile=()=>({...a.getProfile()});
 const equip=item=>{const p=profile();p[item.kind]=item.value;a.saveProfile(p);notice=item.name+' equipped.';a.onChange?.();render();};
 function render(){const s=state();container.replaceChildren();container.append(el('h3','Your collection goals'),el('p','One shared household wardrobe. Finish human rounds or encounters while a goal is pinned. Switching keeps each goal’s partial progress.'));
 if(s.completed>0&&!s.choice){const choice=el('div',undefined,'ck-choice');choice.append(el('strong','Your first reward — choose one to keep'),el('p','The other cape stays available through a three-round goal.'));for(const item of C().items.slice(0,2))choice.append(button('Keep '+item.name,()=>{selected=item.id;a.setState(C().choose(state(),item.id));equip(item);}));container.append(choice);}
 const preview=el('div',undefined,'ck-preview-row'),big=document.createElement('canvas'),small=document.createElement('canvas');big.width=360;big.height=320;small.width=190;small.height=185;big.className=small.className='ck-preview';big.setAttribute('aria-label','Selected cosmetic on your knight');small.setAttribute('aria-label','Actual gameplay-size costume preview');preview.append(big,small);container.append(preview);container.append(el('p','Try-on: '+C().items.find(i=>i.id===selected).name+' · large view and gameplay size. Locked try-ons do not change your saved outfit.','note'));
 const grid=el('div',undefined,'ck-grid');for(const item of C().items){const card=el('article',undefined,'ck-card'),owned=s.owned.includes(item.id),pinned=s.pinned===item.id;card.dataset.pinned=String(pinned);card.append(el('strong',item.name+' · '+item.kind),el('p',item.description));let route=`Complete ${item.goal} rounds or encounters while pinned.`;if(item.id==='rice-guard')route+=' Or finish the main campaign chapter. The Biscuit Toll is optional.';if(item.id==='steve-strut')route+=' Or rescue Steve / complete a Custard Cup.';card.append(el('p',route));const bar=document.createElement('progress');bar.max=item.goal;bar.value=owned?item.goal:s.progress[item.id];bar.setAttribute('aria-label',item.name+' goal progress');card.append(bar,el('p',owned?'Owned'+(s.milestones.some(m=>item.milestones?.includes(m))?' · earned through an adventure or Cup milestone':''):s.progress[item.id]+' / '+item.goal+(pinned?' · Working towards this':' completed')));const row=el('div',undefined,'ck-row');row.append(button('Try it on',()=>{selected=item.id;render();}));if(owned)row.append(button(profile()[item.kind]===item.value?'Equipped':'Equip',()=>equip(item)));else row.append(button(pinned?'Pinned goal':'Work towards this',()=>{notice='Working towards '+item.name+'.';set(C().pin(state(),item.id));}));card.append(row);grid.append(card);}container.append(grid);
 const presets=el('div',undefined,'ck-presets');for(let i=0;i<3;i++){const box=el('div');box.append(el('strong','Outfit '+(i+1)+' '),button('Save',()=>{notice='Outfit '+(i+1)+' saved.';set(C().savePreset(state(),i,profile()));}));const load=button('Wear',()=>{const p=state().presets[i];if(p){a.saveProfile(p);a.onChange?.();notice='Outfit '+(i+1)+' equipped.';render();}});load.disabled=!s.presets[i];box.append(load);presets.append(box);}container.append(presets);
 const tools=el('div',undefined,'ck-row');tools.append(button('Export progress backup',()=>{try{const content=C().exportBackup(localStorage),url=URL.createObjectURL(new Blob([content],{type:'application/json'})),link=document.createElement('a');link.href=url;link.download='custard-knights-progress.json';document.body.append(link);link.click();link.remove();setTimeout(()=>URL.revokeObjectURL(url),1000);notice='Progress backup exported.';}catch(e){notice=e.message;}render();}));
 const file=document.createElement('input');file.type='file';file.accept='.json,application/json';file.hidden=true;file.onchange=async()=>{try{if(file.files[0]){C().importBackup(localStorage,await file.files[0].text());await a.onImport?.();notice='Progress restored. Previously earned items and story spoons were retained.';}}catch(e){notice=e.message;}render();};tools.append(button('Import progress backup',()=>file.click()),file);container.append(tools,el('p','Backup includes story spoons and checkpoints, earned coins, legacy wardrobe, these six goals and four player outfits. Current Cup sessions and settings are not included.','note'));const message=el('p',notice,'ck-message');message.setAttribute('role','status');container.append(message);
 if(raf)cancelAnimationFrame(raf);const draw=now=>{if(!container.isConnected)return;if(now-lastTick>45&&container.getClientRects().length){lastTick=now;const item=C().items.find(i=>i.id===selected),p=profile();p[item.kind]=item.value;try{a.drawPreview(big,p,{gameplay:false,time:now/1000,pose:item.kind==='pose'});a.drawPreview(small,p,{gameplay:true,time:now/1000,pose:item.kind==='pose'});}catch(e){message.textContent='Preview could not draw: '+e.message;}}raf=requestAnimationFrame(draw);};raf=requestAnimationFrame(draw);
 }
 render();return {refresh:render,destroy:()=>{cancelAnimationFrame(raf);container.replaceChildren();}};}
 function reward(container,a,ids=[]){container.replaceChildren();const s=C().normalize(a.getState()),choices=s.completed>0&&!s.choice?C().items.slice(0,2):C().items.filter(i=>ids.includes(i.id));if(!choices.length)return;container.append(el('strong',s.choice?'New costume earned':'Choose your first costume'));for(const item of choices){container.append(button((s.choice?'Equip ':'Choose ')+item.name,()=>{if(!s.choice)a.setState(C().choose(a.getState(),item.id));const p={...a.getProfile(),[item.kind]:item.value};a.saveProfile(p);a.onChange?.();container.replaceChildren(el('p',item.name+' equipped.'));}));}container.append(button('Keep current look',()=>container.replaceChildren()));}
 root.CKCollectionUI={mount,reward};
})(typeof globalThis!=='undefined'?globalThis:this);
