const test=require('node:test'),assert=require('node:assert/strict'),C=require('../game/campaign.js');
function unlockedSave(){const s=C.normalize({});for(const n of C.nodes)s.results[n.id]={spoons:[true,false,false],attempts:1,best:100,assisted:false};return s;}
function harness(id='banquet',options={}){
 const storage={data:null,getItem(){return this.data;},setItem(k,v){this.data=v;}};let finished=[];const c=C.create({storage,onFinish:r=>finished.push(r)});c.restore(unlockedSave());
 const hits=[];const api={makeKnight:o=>({r:22,dead:false,falling:0,inv:0,stun:0,dashT:0,guardLock:0,guard:1.5,vx:0,vy:0,face:0,fx:{},...o}),redraw(){},steer:(e,x,y)=>{const d=Math.hypot(x-e.x,y-e.y)||1;return {x:(x-e.x)/d,y:(y-e.y)/d};},hurt(e,a,d,o){hits.push({e,a,d,o});c.event('hit',{v:e.id,a:a.id,damage:d,src:o.src});e.hp-=d;if(e.hp<=0){e.dead=true;c.event('ko',{v:e.id,a:a.id,src:o.src});}}};
 const g={roundId:'test-round',ents:[api.makeKnight({id:0,human:1,hp:3})],flows:new Map()};c.begin(id,g,api);return {c,g,p:g.ents[0],api,hits,storage,finished,tick(t){g.time-=t;c.tick(t);}};
}
test('main route skips biscuit toll, locked nodes reject launch',()=>{let s=C.normalize({});assert.equal(C.next(s).id,'banquet');assert.equal(C.unlocked(s,'rind'),false);for(const id of ['banquet','puddings','guard'])s=C.award(s,id,{receipt:id,spoons:[true],elapsed:20}).save;assert.equal(C.next(s).id,'bridge');assert.equal(C.unlocked(s,'biscuit'),true);const c=C.create({storage:null});assert.throws(()=>c.begin('rind',{},{}),/locked/);});
test('spoons merge across replays and duplicate receipts never pay twice',()=>{let s=C.normalize({});const a=C.award(s,'banquet',{receipt:'one',spoons:[true,true,false],elapsed:40});assert.deepEqual(a.added,[0,1]);const b=C.award(a.save,'banquet',{receipt:'two',spoons:[true,false,true],elapsed:35});assert.deepEqual(b.save.results.banquet.spoons,[true,true,true]);assert.deepEqual(b.added,[2]);assert.equal(b.save.results.banquet.best,35);const duplicate=C.award(b.save,'banquet',{receipt:'two',spoons:[true,true,true]});assert.equal(duplicate.applied,false);assert.equal(duplicate.save.results.banquet.attempts,2);});
test('save normalization tolerates corruption, malformed spoons and missing versions',()=>{assert.deepEqual(C.normalize({results:{banquet:{spoons:['true',true,1],attempts:-1,best:'bad'}}}).results.banquet,{spoons:[false,true,false],attempts:0,best:null,assisted:false});const c=C.create({storage:{getItem(){return '{broken';},setItem(){throw Error('full');}}});assert.equal(c.next().id,'banquet');c.select('banquet');assert.equal(c.saveError,true);});
test('banquet requires guards AND the exit, rather than KO score',()=>{const h=harness();h.p.score=100;h.tick(.1);assert.equal(h.c.run.status,'playing');for(const e of h.g.ents.slice(1)){e.dead=true;h.c.event('ko',{v:e.id,a:0,src:'sword'});assert.equal(e.respawn,Infinity);}h.tick(2);assert.equal(h.c.run.status,'playing');h.p.x=1100;h.tick(1.6);assert.equal(h.finished[0].won,true);});
test('pudding attackers warn and damage stands; bonking all wave enemies is needed',()=>{const h=harness('puddings');const e=h.g.ents[1],s=h.c.run.stands[0];e.x=s.x;e.y=s.y;h.c.input(e,.1);assert.equal(s.hp,4);assert.ok(h.c.run.warnings.length);h.c.input(e,1.5);assert.equal(s.hp,3);for(const e of h.g.ents.slice(1))e.dead=true;h.tick(.1);assert.equal(h.c.run.wave,2);assert.equal(h.c.run.status,'playing');for(const e of h.g.ents.slice(1))e.dead=true;h.tick(.1);assert.equal(h.finished[0].won,true);assert.equal(h.finished[0].spoons[1],false);});
test('destroying every pudding stand fails without awarding completion',()=>{const h=harness('puddings');h.c.run.stands.forEach(s=>s.hp=0);h.tick(.1);assert.equal(h.finished[0].won,false);assert.deepEqual(h.finished[0].spoons,[false,false,false]);});
test('arrow trial counts actual reflections, grants extra-feat window, keeps archer alive',()=>{const h=harness('biscuit');h.tick(2);assert.equal(h.g.proj.length,1);h.g.ents[1].dead=true;h.c.event('ko',{v:1,a:0,src:'bow'});assert.equal(h.g.ents[1].dead,false);for(let i=0;i<3;i++)h.c.event('reflect',{id:0});h.tick(.1);assert.equal(h.c.run.status,'playing');assert.ok(h.c.run.exitT>h.c.run.elapsed);for(let i=0;i<2;i++)h.c.event('reflect',{id:0});h.tick(.1);assert.equal(h.finished[0].won,true);assert.equal(h.finished[0].spoons[1],true);});
test('bridge sequential checkpoints survive falls; third fall fails',()=>{const h=harness('bridge');h.p.x=1100;h.tick(.1);assert.equal(h.c.run.route,0);h.p.x=440;h.tick(.1);assert.equal(h.c.run.route,1);h.p.dead=true;h.c.event('ko',{v:0,src:'pit'});assert.equal(h.c.run.status,'playing');h.p.dead=false;h.c.event('respawn',{id:0});assert.equal(h.p.x,440);for(let i=0;i<2;i++)h.c.event('ko',{v:0,src:'pit'});assert.equal(h.finished[0].won,false);});
test('bridge cannot finish by skipping gates; dash feat requires crossing the whole gap',()=>{const h=harness('bridge');h.p.x=300;h.p.dashT=.12;h.tick(.1);assert.notEqual(h.c.run.gapDash,true);h.p.x=380;h.tick(.1);assert.equal(h.c.run.gapDash,true);for(const x of [440,760,1100]){h.p.x=x;h.tick(.1);}h.tick(3);assert.equal(h.finished[0].won,true);assert.deepEqual(h.finished[0].spoons,[true,true,true]);});
test('Stirling advances only on actual blocks, then counter, then uncontested pie hold',()=>{const h=harness('stirling');h.p.blocking=true;h.tick(8);assert.equal(h.c.run.phase,0);h.c.event('parry',{id:0});h.c.event('block',{id:0});h.c.event('block',{id:0});h.tick(.1);assert.equal(h.c.run.phase,1);h.g.ents[1].dead=true;h.tick(.1);assert.equal(h.c.run.phase,2);h.p.x=640;h.g.ents[1].x=640;h.g.ents[1].y=440;h.tick(9);assert.equal(h.c.run.status,'playing');h.g.ents.slice(1).forEach(e=>e.dead=true);h.tick(8.1);assert.equal(h.finished[0].won,true);assert.equal(h.finished[0].spoons[1],true);});
test('Steve cage opens only at the actual crate; egg and route are required',()=>{const h=harness('steve');h.c.event('crate',{c:8,r:8,destroyed:true});assert.equal(h.g.pickups.length,0);h.g.grid[8][9]='.';h.c.event('crate',{c:9,r:8,destroyed:true});assert.equal(h.g.pickups[0].kind,'steve');h.p.x=580;h.p.y=300;h.tick(.1);assert.equal(h.c.run.route,0);h.p.fx.steve=10;for(const point of h.c.run.gates){h.p.x=point.x;h.p.y=point.y;h.tick(.1);}assert.equal(h.finished[0].won,true);});
test('Rind telegraphs fixed target, provides punish window and sweep hurts allies',()=>{const h=harness('rind'),b=h.c.run.boss;h.p.inv=0;h.tick(2.5);assert.equal(b.step,'warn');const target={...b.target};h.p.x=180;h.p.y=600;h.tick(1.2);assert.equal(b.step,'exhausted');assert.deepEqual(b.target,target);assert.equal(h.hits.length,0);b.hp=4;h.tick(.1);assert.equal(h.c.run.phase,1);const ally=h.g.ents[2];ally.inv=0;ally.protect=0;ally.x=h.p.x;ally.y=h.p.y;h.tick(2.5);h.p.x=360;h.tick(1.2);assert.ok(h.hits.some(hit=>hit.e===ally));assert.equal(h.c.run.guardsHit,1);assert.equal(h.storage.data.includes('"phase":1'),true);});
test('Rind defeat leads to playable rescue, not immediate success',()=>{const h=harness('rind');h.c.run.boss.dead=true;h.c.event('ko',{v:1,a:0,src:'heavy'});h.tick(.1);assert.equal(h.c.run.phase,2);assert.equal(h.c.run.status,'playing');h.c.event('crate',{c:22,r:8,destroyed:false});assert.equal(h.c.run.status,'playing');h.g.grid[8][22]='.';h.c.event('crate',{c:22,r:8,destroyed:true});assert.equal(h.finished[0].won,true);});
test('boss and exam checkpoint resume reset scripts and cannot earn full-run flawless spoon',()=>{for(const id of ['rind','stirling']){const h=harness(id);const s={...h.c.save,checkpoint:{id,phase:1}};h.c.restore(s);const g={roundId:'resume',ents:[h.api.makeKnight({id:0,human:1})],flows:new Map()};h.c.begin(id,g,h.api,true);assert.equal(h.c.run.phase,1);assert.equal(h.c.run.resumed,true);h.c.finish(true);assert.equal(h.finished[0].spoons[2],false);}});
test('rescue checkpoint resumes with marked living skin and no boss replay',()=>{const h=harness('rind');h.c.restore({...h.c.save,checkpoint:{id:'rind',phase:2}});const g={roundId:'resume-rescue',ents:[h.api.makeKnight({id:0,human:1})],flows:new Map()};h.c.begin('rind',g,h.api,true);assert.equal(h.c.run.phase,2);assert.equal(g.grid[8][22],'x');assert.ok(g.ents.slice(1).every(e=>e.dead));});
test('assistance modifies only campaign health and authored timing',()=>{const h=harness('rind');h.c.assist(true);const g={roundId:'assist',ents:[h.api.makeKnight({id:0,human:1})],flows:new Map()};h.c.begin('rind',g,h.api);assert.equal(g.ents[0].campaignMaxHp,5);h.c.tick(2.5);assert.equal(h.c.run.boss.timer,1.5);h.c.tick(1.6);assert.equal(h.c.run.boss.timer,3.8);});
test('replaying another node never erases an unfinished boss checkpoint',()=>{const h=harness('banquet');h.c.restore({...h.c.save,checkpoint:{id:'rind',phase:1}});h.c.finish(true);assert.deepEqual(h.c.save.checkpoint,{id:'rind',phase:1});const g={roundId:'replay',ents:[h.api.makeKnight({id:0,human:1})],flows:new Map()};h.c.begin('banquet',g,h.api,false);h.c.finish(false);assert.deepEqual(h.c.save.checkpoint,{id:'rind',phase:1});assert.equal(h.c.run.result.checkpoint,null);});
test('campaign backup merge preserves independent spoons and completed chapter ownership',()=>{let a=C.normalize({results:{banquet:{spoons:[true,true,false],attempts:3,best:40}}});const b=C.normalize({results:{banquet:{spoons:[true,false,true],attempts:1,best:35},puddings:{spoons:[true,true,true],attempts:2,best:80}}});const merged=C.merge(a,b);assert.deepEqual(merged.results.banquet.spoons,[true,true,true]);assert.equal(merged.results.banquet.attempts,3);assert.equal(merged.results.banquet.best,35);assert.equal(merged.selected,'guard');assert.deepEqual(merged.results.puddings.spoons,[true,true,true]);});
