const {test}=require('node:test'),assert=require('node:assert/strict'),C=require('../game/collection.js'),P=require('../game/progression.js');
const event=(id,extra={})=>({roundId:id,participated:true,...extra});
const store=()=>{const data=new Map();return {getItem:k=>data.get(k)??null,setItem:(k,v)=>data.set(k,v),removeItem:k=>data.delete(k)};};
test('six concrete signature items with a deterministic route each',()=>{assert.equal(C.items.length,6);assert.deepEqual(C.items.map(i=>i.kind),['cape','cape','blade','helm','helm','pose']);assert.ok(C.items.every(i=>i.goal>0));});
test('first completion offers one choice; duplicate seats/results cannot advance twice',()=>{let s=C.normalize();assert.equal(C.choose(s,'tea-towel').choice,null);s=C.apply(s,event('first')).state;s=C.choose(s,'tea-towel');assert.deepEqual(s.owned,['tea-towel']);assert.equal(C.choose(s,'burnt-toast').choice,'tea-towel');assert.equal(C.apply(s,event('first')).applied,false);assert.equal(C.apply(s,event('spectator',{participated:false})).applied,false);assert.equal(s.completed,1);});
test('goal switches preserve partial progress without awarding past rounds retroactively',()=>{let s=C.pin({},'golden-whisk');s=C.apply(s,event('a')).state;s=C.pin(s,'rooster-crown');s=C.apply(s,event('b')).state;assert.equal(s.progress['golden-whisk'],1);assert.equal(s.progress['rooster-crown'],1);s=C.pin(s,'golden-whisk');for(let i=0;i<7;i++)s=C.apply(s,event('whisk'+i)).state;assert.ok(C.owns(s,'blade','goldenWhisk'));assert.equal(s.progress['rooster-crown'],1);});
test('published story milestones unlock without pinning or duplicate awards',()=>{let r=C.apply({},event('chapter',{milestones:['rice-chapter','steve-rescue']}));assert.deepEqual(r.unlocked,['rice-guard','steve-strut']);r=C.apply(r.state,event('cup',{milestones:['cup-complete']}));assert.deepEqual(r.unlocked,[]);assert.equal(r.state.milestones.length,3);});
test('pure collection awards do not touch legacy ownership or combat properties',()=>{const legacy=P.normalize({earned:250,matches:9,wins:2,unlocked:['blade:fish']}),original=JSON.stringify(legacy);const e={...event('combat'),hp:3,reach:68,damage:1,speed:210};const copy=JSON.stringify(e);C.apply(legacy,e);assert.equal(JSON.stringify(legacy),original);assert.equal(JSON.stringify(e),copy);});
test('three presets persist only appearance fields, never combat',()=>{let s=C.savePreset({},0,{helm:'riceGuard',cape:'teaTowel',pose:'steveStrut',damage:999,hp:99});assert.deepEqual(s.presets[0],{helm:'riceGuard',cape:'teaTowel',pose:'steveStrut'});assert.equal(s.presets.length,3);assert.deepEqual(C.savePreset(s,3,{helm:'great'}),s);});
test('backup restores goals and outfits while retaining existing legacy earned items',()=>{const source=store(),target=store();let state=C.pin({},'golden-whisk');state=C.apply(state,event('one')).state;source.setItem('ck-collection',JSON.stringify(state));source.setItem('ck-progress',JSON.stringify(P.normalize({earned:100,matches:4,wins:1,unlocked:['blade:wooden']})));source.setItem('ck-profile',JSON.stringify({helm:'great',plume:'feather',metal:'gold',emblem:'star',color:'#FF5A4E'}));target.setItem('ck-progress',JSON.stringify(P.normalize({earned:400,matches:12,wins:2,unlocked:['blade:fish']})));C.importBackup(target,C.exportBackup(source));const p=JSON.parse(target.getItem('ck-progress'));assert.equal(p.earned,400);assert.ok(p.unlocked.includes('blade:fish'));assert.ok(p.unlocked.includes('blade:wooden'));assert.equal(JSON.parse(target.getItem('ck-collection')).progress['golden-whisk'],1);assert.equal(C.apply(JSON.parse(target.getItem('ck-collection')),event('one')).applied,false);});
test('malformed backup validates every section before writing',()=>{const s=store();s.setItem('ck-progress','{"earned":40}');const bad={format:'custard-knights-wardrobe',version:1,saves:{'ck-progress':{earned:999,matches:1,wins:1,unlocked:[]},'ck-collection':{version:1,completed:1,owned:['unknown']}}};assert.throws(()=>C.importBackup(s,JSON.stringify(bad)));assert.equal(s.getItem('ck-progress'),'{"earned":40}');for(const data of ['null','[]','not json',JSON.stringify({...bad,version:999})])assert.throws(()=>C.importBackup(s,data));});
test('all goals unlock in their published round counts',()=>{for(const item of C.items){let s=C.pin({},item.id);for(let i=0;i<item.goal;i++)s=C.apply(s,event(item.id+i)).state;assert.ok(C.owns(s,item.kind,item.value));assert.equal(s.completed,item.goal);}});
test('costume drawing and strut transform never mutate combat entities',()=>{
 const vm=require('node:vm'),fs=require('node:fs'),sandbox={};vm.runInNewContext(fs.readFileSync(require.resolve('../game/collection-art.js'),'utf8'),sandbox);const A=sandbox.CKCollectionArt;
 for(const item of C.items){const commands=[],ctx=new Proxy({},{get:(_o,k)=>typeof k==='string'?((...v)=>commands.push([k,...v])):undefined,set:()=>true});const e={id:1,face:Math.PI/2,kit:{helm:'great'},cape:'plain',blade:'steel',pose:'plain',hp:3,reach:68,damage:1,speed:210};if(item.kind==='helm')e.kit.helm=item.value;else e[item.kind]=item.value;Object.freeze(e.kit);Object.freeze(e);const before=JSON.stringify(e);A.drawBack(ctx,e,22,1);A.drawFront(ctx,e,22,1,{results:true});A.pose(ctx,e,22,1,true);if(item.kind==='blade')A.drawWhisk(ctx,43,8);assert.equal(JSON.stringify(e),before);assert.ok(commands.length>0,item.id+' produces actual drawing/pose commands');}
});
test('progress backup merges campaign spoons and checkpoint without losing either device progress',()=>{
 const Campaign=require('../game/campaign.js'),source=store(),target=store();const results=Object.fromEntries(['banquet','puddings','guard','bridge','stirling','steve'].map(id=>[id,{spoons:[true,false,false]}]));
 source.setItem('ck-campaign-v1',JSON.stringify(Campaign.normalize({results,checkpoint:{id:'rind',phase:1}})));target.setItem('ck-campaign-v1',JSON.stringify(Campaign.normalize({results:{banquet:{spoons:[true,true,false]}}})));
 C.importBackup(target,C.exportBackup(source));const combined=JSON.parse(target.getItem('ck-campaign-v1'));assert.deepEqual(combined.results.banquet.spoons,[true,true,false]);assert.equal(combined.checkpoint.id,'rind');assert.equal(combined.checkpoint.phase,1);
});
