// Generated by npm run music; only existing audio files are enabled.
window.CK_SOUNDTRACK={
  "menu": "menu-theme.mp3",
  "courtyard": "audio/02-a-very-noble-food-fight.wav",
  "frost": "audio/03-slippery-when-knighted.wav",
  "factory": "audio/04-the-pie-production-line.wav",
  "dungeon": "audio/05-too-hot-for-armour.wav",
  "roof": "audio/06-mind-the-battlements.wav",
  "bog": "audio/07-bog-standard-heroics.wav",
  "race": "audio/08-run-little-chicken-run.wav",
  "hotpie": "audio/09-pass-the-pie.wav",
  "wardrobe": "audio/10-dressed-to-spill.wav",
  "victory": "audio/11-the-golden-spoon.wav",
  "defeat": "audio/12-another-helping.wav",
  "oh-nae-nae": "audio/13-oh-nae-nae-whats-your-name.wav"
};
