// Generated by npm run music; only existing audio files are enabled.
window.CK_SOUNDTRACK={
  "menu": "menu-theme.mp3",
  "courtyard": null,
  "frost": null,
  "factory": null,
  "dungeon": null,
  "roof": null,
  "bog": null,
  "race": null,
  "hotpie": null,
  "wardrobe": null,
  "victory": null,
  "defeat": null
};
