'use strict';
const fs = require('node:fs'), path = require('node:path');
const projectRoot = path.resolve(__dirname, '..');
const defaultTracks = require('../audio/tracks.json');

function buildCatalog({ rootDir = projectRoot, tracks = defaultTracks } = {}) {
  const catalog = {};
  for (const track of tracks) {
    const basename = track.file.replace(/\.(wav|mp3)$/i, '');
    // Use the downloaded WAV directly. An existing MP3 remains a fallback;
    // there is no requirement to export or manufacture a compressed duplicate.
    const selected = [`${basename}.wav`, `${basename}.mp3`]
      .find(file => fs.existsSync(path.join(rootDir, 'audio', file)));
    catalog[track.id] = selected ? `audio/${selected}` : track.id === 'menu' ? 'menu-theme.mp3' : null;
  }
  return catalog;
}

function writeCatalog(options = {}) {
  const rootDir = options.rootDir || projectRoot;
  const catalog = buildCatalog({ ...options, rootDir });
  fs.writeFileSync(path.join(rootDir, 'audio', 'soundtrack.js'), '// Generated by npm run music; only existing audio files are enabled.\nwindow.CK_SOUNDTRACK=' + JSON.stringify(catalog, null, 2) + ';\n');
  console.log(`Soundtrack: ${Object.values(catalog).filter(Boolean).length}/${Object.keys(catalog).length} tracks available.`);
  return catalog;
}

if (require.main === module) writeCatalog();
module.exports = { buildCatalog, writeCatalog };
