const fs=require('node:fs'),path=require('node:path');
const root=path.resolve(__dirname,'..'),tracks=require('../audio/tracks.json'),catalog={};
for(const t of tracks)catalog[t.id]=fs.existsSync(path.join(root,'audio',t.file))?'audio/'+t.file:t.id==='menu'?'menu-theme.mp3':null;
fs.writeFileSync(path.join(root,'audio','soundtrack.js'),'// Generated by npm run music; only existing audio files are enabled.\nwindow.CK_SOUNDTRACK='+JSON.stringify(catalog,null,2)+';\n');
console.log(`Soundtrack: ${Object.values(catalog).filter(Boolean).length}/${tracks.length} tracks available.`);
