// Actual drawKnight pose playback; fixed entities, 3x slow motion, no gameplay claims.
// node qa/motion-review.cjs OUTPUT.mp4 [runtime-root]
const fs=require('fs'),path=require('path'),os=require('os'),{spawn}=require('child_process');
const ROOT=path.resolve(process.argv[3]||path.join(__dirname,'..')),OUT=path.resolve(process.argv[2]);
const sleep=ms=>new Promise(r=>setTimeout(r,ms));fs.mkdirSync(path.dirname(OUT),{recursive:true});
const profile=fs.mkdtempSync(path.join(os.tmpdir(),'ck-motion-'));
const chrome=spawn(process.env.CHROME||'C:/Program Files/Google/Chrome/Application/chrome.exe',['--headless=new','--remote-debugging-port=0','--user-data-dir='+profile,'--window-size=1280,780','--hide-scrollbars','--mute-audio','about:blank'],{stdio:'ignore',windowsHide:true});
let ws,enc;process.on('exit',()=>{chrome.kill();enc?.kill();});
(async()=>{let port;for(let i=0;i<80;i++){try{port=+fs.readFileSync(path.join(profile,'DevToolsActivePort'),'utf8').split('\n')[0];break;}catch{await sleep(100);}}if(!port)throw Error('Browser unavailable');
 const tab=(await(await fetch(`http://127.0.0.1:${port}/json`)).json()).find(t=>t.type==='page');ws=new WebSocket(tab.webSocketDebuggerUrl);let id=0;const pending=new Map();
 ws.onmessage=m=>{const d=JSON.parse(m.data),p=pending.get(d.id);if(p){pending.delete(d.id);d.error?p.reject(Error(JSON.stringify(d.error))):p.resolve(d.result);}};await new Promise(r=>ws.onopen=r);
 const send=(method,params={})=>new Promise((resolve,reject)=>{const n=++id;pending.set(n,{resolve,reject});ws.send(JSON.stringify({id:n,method,params}));});
 const run=async expression=>{const r=await send('Runtime.evaluate',{expression,awaitPromise:true,returnByValue:true});if(r.exceptionDetails)throw Error(JSON.stringify(r.exceptionDetails));return r.result.value;};
 await send('Emulation.setDeviceMetricsOverride',{width:1280,height:780,deviceScaleFactor:1,mobile:false});await send('Page.navigate',{url:'file:///'+path.join(ROOT,'index.html').replace(/\\/g,'/')+'?qa=1'});
 for(let i=0;i<100;i++){await sleep(100);if(await run('!!window.CK'))break;}
 await run('CK.freeze(true);CK.sprLoadAll()');
 await run(`(()=>{CK.begin({humans:0});CK.sprites(true);CK.G().clock=1;CK.G().over=false;const c=document.createElement('canvas');c.width=1280;c.height=780;c.style.cssText='position:fixed;inset:0;z-index:99999';document.body.append(c);const x=c.getContext('2d');window.paintMotion=t=>{x.fillStyle='#eee5d4';x.fillRect(0,0,1280,780);x.fillStyle='#291d36';x.font='bold 27px Arial';x.fillText('Sword grip and motion — actual game renderer',34,43);x.font='17px Arial';x.fillText('3× slow motion · fixed pose review · combat rules unchanged',34,74);const cycle=t%2;[['Light','light',.22],['Heavy','heavy',.3],['Dash-stab','stab',.18],['Shield bash','bash',.18]].forEach(([label,kind,dur],k)=>{const cx=160+k*320,elapsed=(cycle-.45)/3,active=elapsed>=0&&elapsed<dur;let state=kind==='heavy'&&cycle<.45?'CHARGE':active?(elapsed<=.06?'WIND-UP':elapsed<dur-.06?'CONTACT':'RECOVERY'):'READY';x.font='bold 23px Arial';x.textAlign='center';x.fillText(label,cx,123);x.font='14px Arial';x.fillText(state,cx,149);for(const [yy,face,scale] of [[330,Math.PI/4,2.25],[540,0,2.25],[700,Math.PI/4,1]]){const e=CK.mkKnight({id:42,color:'#FF5A4E',kit:{helm:'great',plume:'feather',metal:'steel'},blade:'steel',cape:'plain',emblem:'star',face,swingKind:kind,swingDur:dur,swing:active?dur-elapsed:0,heavyReach:kind==='heavy',charge:kind==='heavy'&&cycle<.45?.35*cycle/.45:0});CK.withCtx(x,()=>{x.save();x.translate(cx,yy);x.scale(scale,scale);CK.drawKnight(e);x.restore();});}x.textAlign='start';});x.font='15px Arial';x.fillText('Enlarged southeast / east, with native drawing scale below',34,759);};})()`);
 enc=spawn('ffmpeg',['-y','-loglevel','error','-f','image2pipe','-framerate','30','-vcodec','mjpeg','-i','pipe:0','-an','-c:v','libx264','-preset','fast','-crf','18','-pix_fmt','yuv420p','-movflags','+faststart',OUT],{stdio:['pipe','ignore','pipe'],windowsHide:true});let err='';enc.stderr.on('data',d=>err+=d);const ended=new Promise((resolve,reject)=>{enc.on('error',reject);enc.on('exit',c=>c===0?resolve():reject(Error(err)));});
 for(let f=0;f<240;f++){await run('paintMotion('+f/30+')');const shot=await send('Page.captureScreenshot',{format:'jpeg',quality:94});const bytes=Buffer.from(shot.data,'base64');if(f===24)fs.writeFileSync(OUT.replace(/\.mp4$/,'.jpg'),bytes);if(!enc.stdin.write(bytes))await new Promise(r=>enc.stdin.once('drain',r));}
 enc.stdin.end();await ended;enc=null;ws.close();chrome.kill();console.log(OUT);
})().catch(e=>{console.error(e);ws?.close();chrome.kill();enc?.kill();process.exitCode=1;});
