(async()=>{
 const passed=[],check=(value,label)=>{if(!value)throw Error(label);passed.push(label);};
 await document.fonts.ready;await CK.sprLoadAll();
 check(CK.spritesReady(),'Default sprite atlases decoded');
 const seats=[{dev:'pad',idx:2},{dev:'kb1'},{dev:'pad',idx:0},{dev:'kb2'}];
 CK.cfg.players=4;CK.setSeats(seats);CK.start();
 for(let i=0;i<5;i++){CK.endMatch();CK.rematch();}
 check(JSON.stringify(CK.seats())===JSON.stringify(seats),'Five rematches preserve non-sequential controller assignments');
 CK.start();check(CK.seats()===null,'A fresh quick-play start clears party assignments');
 CK.begin({humans:4,map:'courtyard',mode:'ffa'});
 CK.G().ents[1].parries=10;CK.G().ents[1].score=12;
 const before=CK.PROG.matches;CK.endMatch();
 check(CK.PROG.matches===before+1&&CK.PROG.ch.parry10===10,'Second couch seat contributes to shared progress');
 const earned=CK.PROG.earned;CK.endMatch();check(CK.PROG.earned===earned,'Repeated local end does not grant twice');
 CK.NET.role='client';CK.NET.peer={id:'test-guest'};
 const setup=CK.netSetup();setup.roundId='test-guest-'+crypto.randomUUID();setup.ents[3].netId='test-guest';
 CK.clientRecv({t:'start',setup});
 const guestBefore=CK.PROG.matches;
 CK.clientRecv({t:'end',roundId:'stale',results:[]});check(!CK.G().over,'Stale online result is ignored');
 const result={t:'end',roundId:setup.roundId,results:[{id:3,mode:'ffa',won:false,coins:7,parries:10,ringouts:3,lava:5},{id:0,mode:'ffa',won:true,coins:99,parries:0,ringouts:0,lava:0}]};
 CK.clientRecv({...result,results:[result.results[0],result.results[0]]});
 check(!CK.G().over&&CK.PROG.matches===guestBefore,'Duplicate knight results cannot end a round or stack challenges');
 CK.clientRecv({...result,results:[{...result.results[0],parries:-2}]});
 check(!CK.G().over,'Malformed combat results allow a later valid result');
 const guestRound=CK.G();CK.clientRecv({t:'start',setup});check(CK.G()===guestRound,'Duplicate start preserves the active round');
 const oldClock=CK.G().clock;CK.clientRecv({t:'s',roundId:'stale',cl:900});check(CK.G().clock===oldClock,'Stale snapshots cannot mutate a current round');
 CK.clientRecv(result);
 check(CK.PROG.matches===guestBefore+1&&CK.PROG.ch.lava5===5&&CK.PROG.ch.ringout3===3,'Guest receives authoritative combat challenge results');
 check(CK.PROG.earned===earned+7,'Guest awards only its own knight result');
 CK.clientRecv(result);check(CK.PROG.matches===guestBefore+1,'Duplicate online packet is ignored');
 CK.NET.role='host';CK.NET.peer=null;CK.NET.players=[{id:'host'},{id:'guest',name:'Guest'}];CK.cfg.players=1;
 const connection={peer:'guest',open:true,send:()=>{}};CK.NET.conns.set('guest',connection);CK.start();CK.freeze(true);
 CK.hostRecv(connection,{t:'in',roundId:'old-round',i:[1,0,1,0,0,1,0]});
 check(!CK.NET.inputs.guest,'Old-round guest input is ignored');
 CK.hostRecv(connection,{t:'in',roundId:CK.G().roundId,i:[1,0,1,0,0,1,0]});
 check(CK.NET.inputs.guest[0]===1,'Active guest input reaches its assigned knight');
 CK.endMatch();CK.rematch();CK.freeze(true);
 check(!CK.NET.inputs.guest&&!CK.NET.latch.guest,'Rematch clears held guest input and action latches');
 CK.NET.latch.guest={a:1};CK.hostDrop('guest');
 check(!CK.NET.latch.guest&&CK.G().ents.every(e=>e.netId!=='guest')&&CK.G().ents[1].human===0,'Guest drop clears controls and gives its knight to a bot');
 const active=CK.G();CK.cfg.players=4;CK.NET.players=Array.from({length:6},(_,i)=>({id:'p'+i,name:'Knight'}));CK.start();
 check(CK.G()===active&&document.getElementById('lobbyMsg').textContent.includes('Too many'),'Over-capacity settings cannot evict accepted guests');
 CK.NET.role=null;CK.NET.peer=null;CK.NET.conns.clear();CK.NET.players=[];CK.cfg.players=2;CK.setSeats([{dev:'kb2'},{dev:'kb1'}]);CK.start();CK.freeze(true);CK.keys.KeyD=true;
 check(CK.humanInput(1).mx===0&&CK.humanInput(2).mx===1,'Keyboard halves follow explicit party seats');
 CK.keys.KeyD=false;CK.freeze(true);
 CK.begin({humans:0});for(let i=0;i<3000;i++)CK.sfx('boom');
 check(CK.audioStats().active<=CK.audioStats().max,'Sound-effect bursts are bounded to 64 active voices');
 const drainStarted=performance.now(),audioDrain=[];
 do{audioDrain.push({ms:Math.round(performance.now()-drainStarted),active:CK.audioStats().active});if(CK.audioStats().active===0)break;await new Promise(r=>setTimeout(r,50));}while(performance.now()-drainStarted<5000);
 check(CK.audioStats().active===0,'Completed sound graphs are disconnected');
 CK.cueMusic('courtyard');check(CK.musicState().src==='audio/02-a-very-noble-food-fight.wav'&&CK.musicState().wanted,'Courtyard selects its installed WAV soundtrack');
 CK.cueMusic('wardrobe');check(CK.musicState().src==='audio/10-dressed-to-spill.wav'&&CK.musicState().wanted,'Wardrobe selects its installed WAV soundtrack');
 const originalTracks={courtyard:window.CK_SOUNDTRACK.courtyard,wardrobe:window.CK_SOUNDTRACK.wardrobe};
 try{
  delete window.CK_SOUNDTRACK.courtyard;delete window.CK_SOUNDTRACK.wardrobe;
  CK.cueMusic('courtyard');check(!CK.musicState().wanted,'Missing soundtrack exports remain disabled');
  CK.cueMusic('wardrobe');check(CK.musicState().src==='menu-theme.mp3'&&CK.musicState().wanted,'Missing wardrobe track falls back to the original menu theme');
 }finally{Object.assign(window.CK_SOUNDTRACK,originalTracks);}
 CK.cfg.mode='race';CK.cfg.map='roof';CK.start();
 check(CK.musicState().cue==='race'&&CK.musicState().src==='audio/08-run-little-chicken-run.wav'&&CK.musicState().wanted,'Installed race WAV takes priority over the arena');
 CK.cueMusic(null);CK.freeze(true);
 return {passed,audioDrain};
})()
